AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'lib'
    - 'spec'
  Exclude:
    - 'spec/rails_app/**/*'
    - 'spec/spec_helper.rb'
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/LineLength:
  Max: 100
